# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9d0836fca3ecbe69b6fc18a6d1595e88ca7e175e23a88e52c8f0dfa8629c95827cfefb81acb26d6782a3edf9d36a04555b46642a90aaac6ed3b16f957bdcd4ee

test:
  secret_key_base: d6fd6a783798f01beeb6ed410cd1b71fef4633e818a97c5e55728129b300e25bcfaecebe47d7bd17c1127a2ee0e72bf492aa84c2a31c1b57a11e4f75a168c339

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
